name: codecov.yml
on:
  pull_request:

jobs:
  test-code-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}


      - uses: php-actions/composer@v6
        with:
          args: "--ignore-platform-reqs --no-scripts"
          working_dir: "src"


      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: pdo, pdo_mysql, opcache, redis, mysql
          coverage: xdebug


      - name: Install Dependencies
        working-directory: "src"
        run: |
          touch database/database.sqlite
          cp .env.example .env
          php artisan key:generate
          php artisan config:cache
          php artisan migrate:fresh --seed


      - name: PHPUnit Tests
        working-directory: "src"
        env:
          XDEBUG_MODE: coverage
        run: |
          vendor/bin/phpunit --coverage-clover ./coverage.xml


      - name: Coverage report
        uses: kloostermanw/code-coverage@master
        with:
          file: ./src/coverage.xml
          github-token: ${{ secrets.GITHUB }}
          with-chart: false
          min-line-coverage: 60


      - name: Publish coverage report to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./src/coverage.xml
